name: eternapix
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bitcoin_icons: ^0.0.1
  font_awesome_flutter: ^10.7.0
  full_picker: ^2.1.0
  curved_navigation_bar: ^1.0.6
  path: ^1.9.0
  image_picker: ^1.1.2
  firebase_core: ^3.4.1
  image_cropper: ^5.0.1
  image_cropper_platform_interface: ^5.0.0
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1
  firebase_storage: ^12.3.0
  cached_network_image: ^3.4.1
  dio: ^5.6.0
  permission_handler: ^11.3.1
  get: ^4.6.6
  babstrap_settings_screen: ^0.1.7
  katana_form: ^2.13.8
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  intl_utils: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NameApp
      fonts:
        - asset: assets/fonts/AppBar - ArianaVioleta-dz2K.ttf
    - family: AppBarHome
      fonts:
        - asset: assets/fonts/AppBar - Nasa21-l23X.ttf
