// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPS8g9Fg0bvbsLSn3SIWDtwHrHNcYqtX8',
    appId: '1:556844508676:web:07041d6f4fe6f5afa43751',
    messagingSenderId: '556844508676',
    projectId: 'eternapixs',
    authDomain: 'eternapixs.firebaseapp.com',
    storageBucket: 'eternapixs.appspot.com',
    measurementId: 'G-V1J2SH9TQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDNxaiMK7DZIYgQU3fam_6ZGgDUHKl3e4',
    appId: '1:556844508676:android:76bad64ad336ba0fa43751',
    messagingSenderId: '556844508676',
    projectId: 'eternapixs',
    storageBucket: 'eternapixs.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPS8g9Fg0bvbsLSn3SIWDtwHrHNcYqtX8',
    appId: '1:556844508676:web:07041d6f4fe6f5afa43751',
    messagingSenderId: '556844508676',
    projectId: 'eternapixs',
    authDomain: 'eternapixs.firebaseapp.com',
    storageBucket: 'eternapixs.appspot.com',
    measurementId: 'G-V1J2SH9TQ5',
  );
}
